version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: app-mercafacil
    ports:
      - "3001:3000"
    environment:
      - HOST=0.0.0.0
    volumes:
    - .:/home/node/app
    depends_on:
      - mysql
      - postgresql
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  postgresql:
    image: postgres
    ports:
      - "5438:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
